[package]
name = "bird"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
# cmd_lib = "1.3.0"
# sha2 = "0.10.2"
anyhow = "1.0.57"
# thiserror = "1.0.31"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
# reqwest = { version = "0.11", features = ["blocking", "json"] }
clap = { version = "3.1.18", features = ["derive", "env"] }
dialoguer = "0.10.1"
log = "0.4.17"
fern = "0.6.1"
chrono = { version = "0.4.19", features = ["serde"] }
