name: Release
on:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            deb: true

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            deb: true

          - os: macos-latest
            target: x86_64-apple-darwin

          - os: macos-latest
            target: aarch64-apple-darwin

          - os: windows-latest
            target: x86_64-pc-windows-msvc

          - os: windows-latest
            target: aarch64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }}
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get version
        id: bird_version
        uses: SebRollen/toml-action@v1.0.0
        with:
          file: Cargo.toml
          field: package.version

      - name: Set artifact name
        shell: bash
        run: |
          version="$(git describe --tags --abbrev=0)"
          name="bird-$version-${{ matrix.target }}"
          echo "ARTIFACT_NAME=$name" >> $GITHUB_ENV
          echo "version: $version"
          echo "artifact: $name"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v1

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target=${{ matrix.target }} --color=always --verbose
          use-cross: ${{ runner.os == 'Linux' }}

      - name: Install cargo-deb
        if: ${{ matrix.deb == true }}
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb

      - name: Build deb
        if: ${{ matrix.deb == true }}
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --no-build --no-strip --output=. --target=${{ matrix.target }}

      - name: Package (Unix)
        if: runner.os != 'Windows'
        run: >
          tar -cv
          README.md LISCENCE
          -C target/${{ matrix.target }}/release/ bird
          | gzip --best
          > 'bird-${{ steps.get_version.outputs.value }}-${{ matrix.target }}.tar.gz'

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: >
          7z a 'bird-${{ steps.get_version.outputs.value }}-${{ matrix.target }}.zip'
          README.md LISCENCE
          ./target/${{ matrix.target }}/release/bird.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: |
            *.deb
            *.tar.gz
            *.zip
